version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_net
    container_name: Client

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    networks:
      - app_net
    container_name: Locust

networks:
  app_net:
    driver: bridge
